### ISSUE TITLE
Client and server crash in some cases when the connection is lost

### ISSUE THREAD

**Issue by Lobachevskiy** [Lobachevskiy/constricting-snake-chat#1]
server:

> Traceback (most recent call last):
>   File "C:\Users\Admin\Desktop\Chat\server.py", line 31, in chat_server
>     data = socket.recv(BUFF_SIZE)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Admin\Desktop\Chat\server.py", line 60, in <module>
>     sys.exit(chat_server())
>   File "C:\Users\Admin\Desktop\Chat\server.py", line 41, in chat_server
>     broadcast("Client (%s, %s) disconnected.\n" % addr,
> NameError: name 'addr' is not defined

client:

> Traceback (most recent call last):
>   File "C:\Users\Admin\Desktop\Chat\client.py", line 43, in <module>
>     sys.exit(chat_client())
>   File "C:\Users\Admin\Desktop\Chat\client.py", line 37, in chat_client
>     server_socket.send(sys.stdin.readline().encode())
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by Lobachevskiy** [comment]
Fixed 1b13b42c73c2cd6bcca5d8819a7550327990271b
